local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Onurhan Hub | [ 🤖 UPDATE] Ball Blade", "DarkTheme")
local Tab = Window:NewTab("Attack")
local Section = Tab:NewSection("")
Section:NewButton("Auto Block", "Auto Block", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/1f0yt/community/main/AutoBlock"))()
    print("Clicked")
end)
