local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("SensatioX Hub | update BETA V1.2")
local Tab = Window:NewTab("Attack")
local Section = Tab:NewSection("")
Section:NewButton("Auto parry", "Auto Parry", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/1f0yt/community/main/AutoBlock"))()
    print("Clicked")
end)
