local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("SensatioX Hub | update BETA V1.2")
local Tab = Window:NewTab("settings")
local Tab = Window:NewTab("coming")
local Section = Tab:NewSection("open")
Section:NewButton("Auto Block", "Auto Block", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/1f0yt/community/main/AutoBlock"))()
    print("Clicked")
end)
